### ISSUE TITLE
main.py Line 5 import issue

### ISSUE THREAD

**Issue by googleadmin1** [nathanlopez/Stitch#11]
Here is the error::
Traceback (most recent call last):
  File "./main.py", line 5, in <module>
    from Application.stitch_cmd import *
  File "/Users/Desktop/Stitch-master/Application/stitch_cmd.py", line 5, in <module>
    import stitch_winshell
ImportError: No module named 'stitch_winshell'

I am still new to python. I am really liking this project and its potential. I am finding the coding of this project to be a bit easier to digest than a couple of the others. However this issue confuses me. 

I hope someone may be able to point me in the right direction.

**Comment by iosdec** [comment]
+1 on this, any response @nathanlopez ? looking forward to testing Stitch! :)

**Comment by iosdec** [comment]
I've just fixed the error that I had and Stitch is working perfectly - maybe I can help you @googleadmin1 . Is that the full error log?

**Comment by s1st3r** [comment]
stitchvars have to be intact. If you changes stuff there, you gotta make sure they match.

**Comment by 4g0tt3nSou1** [comment]
Sorry to necro, Have this error. Was looking to see if there was any fix?

Also that is the full error, Here is mine for context

https://pastebin.com/LJbiAyY6

only modification was I commented out a print statement causing an error when running main.py, in 
https://pastebin.com/dYSgCRHY
