### ISSUE TITLE
Payload does not install (host machine)

### ISSUE THREAD

**Issue by exist** [nathanlopez/Stitch#30]
Generates error:
`Traceback (most recent call last):
  File "st_main.py", line 1, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "requirements.pyc", line 15, in <module>
ImportError: No module named requests
`
Its a VM.

**Comment by DeliriousGod** [comment]
You need to download the module 'requests' by opening the terminal or cmd and typing 'pip install requests'. If it doesn't work then you need to find it on the internet and download it.
