### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by iii235** [nathanlopez/Stitch#38]
I manually installed all the dependencies for Kali Linux. When I run main.py using python3, I get this error: Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from Application.stitch_cmd import *
  File "/home/kali/Stitch/Application/stitch_cmd.py", line 70
    print ""
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

**Comment by iii235** [comment]
Nevermind, I fixed the code manually. I have a new problem now.

**Comment by iii235** [comment]
When I run main.py again, I get this: Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from Application.stitch_cmd import *
  File "/home/kali/Stitch/Application/stitch_cmd.py", line 5, in <module>
    import stitch_winshell
ModuleNotFoundError: No module named 'stitch_winshell'
And when I run this (python3 -m pip install stitch_winshell), it doesn't find the module. I can't even use the requirements.txt because everything locks up at the email module.

**Comment by iii235** [comment]
What happens when I try to use lnx_requirements:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-midq8f81/email/setup.py'"'"'; __file__='"'"'/tmp/pip-install-midq8f81/email/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-midq8f81/email/pip-egg-info                                          
         cwd: /tmp/pip-install-midq8f81/email/                               
    Complete output (11 lines):                                              
    Traceback (most recent call last):                                       
      File "<string>", line 1, in <module>                                   
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 18, in <module>                                                                  
        import setuptools.version                                            
      File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>                                                                    
        import pkg_resources                                                 
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 36, in <module>                                                               
        import email.parser                                                  
      File "/tmp/pip-install-midq8f81/email/email/parser.py", line 10, in <module>                                                                        
        from cStringIO import StringIO                                       
    ModuleNotFoundError: No module named 'cStringIO'                         
    ----------------------------------------                                 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by demoncode-cyber** [comment]
Same

**Comment by ShailMurtaza** [comment]
> 
> 
> What happens when I try to use lnx_requirements:
> ERROR: Command errored out with exit status 1:
> command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-midq8f81/email/setup.py'"'"'; **file**='"'"'/tmp/pip-install-midq8f81/email/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-midq8f81/email/pip-egg-info
> cwd: /tmp/pip-install-midq8f81/email/
> Complete output (11 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/lib/python3/dist-packages/setuptools/**init**.py", line 18, in
> import setuptools.version
> File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in
> import pkg_resources
> File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 36, in
> import email.parser
> File "/tmp/pip-install-midq8f81/email/email/parser.py", line 10, in
> from cStringIO import StringIO
> ModuleNotFoundError: No module named 'cStringIO'
> ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I think this Rat is only compatible with **python2**
