### ISSUE TITLE
Installation Problem (Windows)

### ISSUE THREAD

**Issue by ManagerBitten** [nathanlopez/Stitch#46]
Im not sure how to fix this because i havent seen any issue with it

C:\Users\dillp\Downloads\Stitch-master\Stitch-master>pip install -r win_requirements.txt
Collecting colorama==0.3.7
  Using cached colorama-0.3.7-py2.py3-none-any.whl (19 kB)
Collecting email==4.0.2
  Using cached email-4.0.2.tar.gz (1.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dillp\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dillp\\AppData\\Local\\Temp\\pip-install-7ndkds4l\\email_4152e713dcfe436f9f0a55d8771090c2\\setup.py'"'"'; __file__='"'"'C:\\Users\\dillp\\AppData\\Local\\Temp\\pip-install-7ndkds4l\\email_4152e713dcfe436f9f0a55d8771090c2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dillp\AppData\Local\Temp\pip-pip-egg-info-dyolyek2'
         cwd: C:\Users\dillp\AppData\Local\Temp\pip-install-7ndkds4l\email_4152e713dcfe436f9f0a55d8771090c2\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dillp\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 16, in <module>
        import setuptools.version
      File "c:\users\dillp\appdata\local\programs\python\python39\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "c:\users\dillp\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 33, in <module>
        import email.parser
      File "C:\Users\dillp\AppData\Local\Temp\pip-install-7ndkds4l\email_4152e713dcfe436f9f0a55d8771090c2\email\parser.py", line 10, in <module>
        from cStringIO import StringIO
    ModuleNotFoundError: No module named 'cStringIO'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/e7/816030d3b0426c130040bd068be62b9213357ed02896f5d9badcf46d1b5f/email-4.0.2.tar.gz#sha256=e2254c9b4e4cf33553f7dfc85b500eea4c3e96733736f38c9dbfc3dcc6303705 (from https://pypi.org/simple/email/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement email==4.0.2 (from versions: 2.5.8, 3.0.1, 4.0.1, 4.0.2, 6.0.0a1)
ERROR: No matching distribution found for email==4.0.2

**Comment by kanubhai12** [comment]
Ok

**Comment by Icicles0** [comment]
Me to.
