### ISSUE TITLE
Error when pip install -r lnx_requirements.txt on Debian (Latest)

### ISSUE THREAD

**Issue by imABitSpecial** [nathanlopez/Stitch#48]
Here is the error
```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ycuy40c_/email_feb9100879314ea3979e6dacef0ece69/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ycuy40c_/email_feb9100879314ea3979e6dacef0ece69/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fb5hvejm
         cwd: /tmp/pip-install-ycuy40c_/email_feb9100879314ea3979e6dacef0ece69/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 33, in <module>
        import email.parser
      File "/tmp/pip-install-ycuy40c_/email_feb9100879314ea3979e6dacef0ece69/email/parser.py", line 10, in <module>
        from cStringIO import StringIO
    ModuleNotFoundError: No module named 'cStringIO'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/e7/816030d3b0426c130040bd068be62b9213357ed02896f5d9badcf46d1b5f/email-4.0.2.tar.gz#sha256=e2254c9b4e4cf33553f7dfc85b500eea4c3e96733736f38c9dbfc3dcc6303705 (from https://pypi.org/simple/email/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement email==4.0.2
ERROR: No matching distribution found for email==4.0.2
```

**Comment by imABitSpecial** [comment]
~~Now getting a new error after trying on a new installation
![image](https://user-images.githubusercontent.com/88986045/129503474-3c162b4b-2858-49d3-8ee0-2cab3fc439e2.png)~~

Edit: Fixed

**Comment by imABitSpecial** [comment]
Another update: went through and manually installed what I could from lnx_requirements.txt

Did not install:
- Readline
- Logging

Did not exist:
- PIL
- Email

**Comment by imABitSpecial** [comment]
![image](https://user-images.githubusercontent.com/88986045/129505326-51959a94-286a-47e5-93fb-7e9986228585.png)

**Comment by imABitSpecial** [comment]
Yet another update.

I tried on my host pc and this happened.
![image](https://user-images.githubusercontent.com/88986045/129508064-b6deb3a6-65a0-4dc9-aab3-e7799ea5d355.png)

**Comment by ViCrack** [comment]
Requirements

    Python 2.7

Requirements

    Python 2.7
