### ISSUE TITLE
Problem with main.py / stitch_cmd.py

### ISSUE THREAD

**Issue by fembric** [nathanlopez/Stitch#63]
python3 main.py
Traceback (most recent call last):
  File "/home/star/Stitch/main.py", line 5, in <module>
    from Application.stitch_cmd import *
  File "/home/star/Stitch/Application/stitch_cmd.py", line 5, in <module>
    import stitch_winshell
ModuleNotFoundError: No module named 'stitch_winshell'

**Comment by kanubhai12** [comment]
😏😩😫
