### ISSUE TITLE
Error when installing requirements | Fedora 38 Workstation

### ISSUE THREAD

**Issue by vapmawtf** [nathanlopez/Stitch#68]
```
(.venv) ╭─riviox@fedora ~/Dokumenty/Stitch  ‹master*› 
╰─➤  pip install -r lnx_req*  
Collecting colorama==0.3.7 (from -r lnx_requirements.txt (line 1))
  Using cached colorama-0.3.7-py2.py3-none-any.whl (19 kB)
Collecting email==4.0.2 (from -r lnx_requirements.txt (line 2))
  Using cached email-4.0.2.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/riviox/Dokumenty/Stitch/.venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/riviox/Dokumenty/Stitch/.venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/riviox/Dokumenty/Stitch/.venv/lib64/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-po3i6f45/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-po3i6f45/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-po3i6f45/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-po3i6f45/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "/tmp/pip-install-27oa4a1l/email_9beb8c8cb8574058baea0e4307a346ce/ez_setup.py", line 91
          except pkg_resources.VersionConflict, e:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(.venv) ╭─riviox@fedora ~/Dokumenty/Stitch  ‹master*› 
╰─➤                                                                         1 ↵

```
I have this error everytime

**Comment by vapmawtf** [comment]
wait, i use Python 3.11.4....
