### ISSUE TITLE
HELP please i cant figure this out 

### ISSUE THREAD

**Issue by thekillerlvl900** [nathanlopez/Stitch#72]
im trying to install win_requirments.txt ik i need python 2.7 but im using python 3.12 beceasue it has pip and for some reason python 2.7 doesnt have pip so please someone help 

`C:\Windows\System32\Stitch>pip -v install -r win_requirements.txt
Using pip 24.0 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip (python 3.12)
Defaulting to user installation because normal site-packages is not writeable
Collecting colorama==0.3.7 (from -r win_requirements.txt (line 1))
  Obtaining dependency information for colorama==0.3.7 from https://files.pythonhosted.org/packages/b7/8e/ddb32ddaabd431813e180ca224e844bab8ad42fbb47ee07553f0ec44cd86/colorama-0.3.7-py2.py3-none-any.whl.metadata
  Using cached colorama-0.3.7-py2.py3-none-any.whl.metadata (13 kB)
Collecting email==4.0.2 (from -r win_requirements.txt (line 2))
  Using cached email-4.0.2.tar.gz (1.2 MB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
  Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
  Installing collected packages: setuptools
  Successfully installed setuptools-69.5.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ryank\AppData\Local\Temp\pip-build-env-ifdfs658\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ryank\AppData\Local\Temp\pip-build-env-ifdfs658\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\ryank\AppData\Local\Temp\pip-build-env-ifdfs658\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\ryank\AppData\Local\Temp\pip-build-env-ifdfs658\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
    File "C:\Users\ryank\AppData\Local\Temp\pip-install-97mpojj4\email_52af59345a8b476689343e4225f873c1\ez_setup.py", line 91
      except pkg_resources.VersionConflict, e:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  SyntaxError: multiple exception types must be parenthesized
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\ryank\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\ryank\AppData\Local\Temp\tmpuy_azy2w'
  cwd: C:\Users\ryank\AppData\Local\Temp\pip-install-97mpojj4\email_52af59345a8b476689343e4225f873c1
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Windows\System32\Stitch>`

**Comment by MilesElsie** [comment]
I also got these problems, What's the fixing way?
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-zb5wp2ur\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-zb5wp2ur\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-zb5wp2ur\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-build-env-zb5wp2ur\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
        File "C:\Users\xxxxxx\AppData\Local\Temp\pip-install-7d7qp8ss\email_17484898f24b4ab696591185ea0b3dde\ez_setup.py", line 91
          except pkg_resources.VersionConflict, e:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
